### ISSUE TITLE
is there any docs for explaining what is this driver use for and how to use?

### ISSUE THREAD

**Issue by Doerthous** [etnaviv/galcore_headers#2]
how can I use gcoOS_GetDisplayByIndex defined in gc_hal_platform.h?

**Comment by austriancoder** [comment]
This repository is _ONLY_ a collection of header files for the closed source Vivanten galcore driver.

It is used to figure out some details that could help reverse engineering the closed source driver.

We do _NOT_ provide any support for the binary blob driver - ask your SoC or board vendor!

You might want to try etnaviv (found in mesa and the Linux kernel driver).

**Comment by Doerthous** [comment]
Ok, I got it
